package vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;

public class PanelTratamiento extends javax.swing.JPanel {
    public PanelTratamiento() {
        initComponents();
        bloquearCampos();
        inicializarCombosHora();
    }
    private void inicializarCombosHora() {
    horaCombo.removeAllItems();
    for (int h = 0; h < 24; h++) {
        horaCombo.addItem(String.format("%02d", h));
    }

    minCombo.removeAllItems();
    minCombo.addItem("00");
    minCombo.addItem("15");
    minCombo.addItem("30");
    minCombo.addItem("45");
}

    public javax.swing.JButton getEditarBtn() {
      return editarBtn;
    }

  
    public javax.swing.JTextField getNombreTxt() { 
        return nombreTxt; 
    }
    
    public javax.swing.JTextField getRutTxt() { 
        return rutTxt; 
    }
    
    public javax.swing.JTextField getDietaTxt() { 
        return dietaTxt; 
    }
    
    public javax.swing.JTextField getMedsTxt() { 
        return medsTxt; 
    }

    public JCheckBox getSosCheck() {
        return sosCheck;
    }

    public JCheckBox getInsulinaCheck() {
        return insulinaCheck;
    }
    
    
    
    
    
    public javax.swing.JTextField getDosisTxt() { 
        return dosisTxt; 
    }
    
    public javax.swing.JTextField getFreqTxt() { 
        return freqTxt; 
    }

    
    
    
    
    public javax.swing.JButton getVolverBtn() { 
        return volverBtn; 
    }

    public JButton getSaveTtoBtn() {
        return saveTtoBtn;
    }
    
    
    public void habilitarDosisLenta(boolean habilitar) {
    dosisTxt.setEnabled(habilitar);
    }
    public void limpiarDosis() {
        dosisTxt.setText("");
    }
    
public void modoLectura() {
    insulinaCheck.setEnabled(false);
    sosCheck.setEnabled(false);

    dietaTxt.setEditable(false);
    medsTxt.setEditable(false);
    freqTxt.setEditable(false);

    horaCombo.setEnabled(false);
    minCombo.setEnabled(false);

    saveTtoBtn.setEnabled(false);
    editarBtn.setEnabled(true);

    habilitarDosisLenta(insulinaCheck.isSelected());
}


public void modoEdicion() {
    insulinaCheck.setEnabled(true);
    sosCheck.setEnabled(true);

    dietaTxt.setEditable(true);
    medsTxt.setEditable(true);
    freqTxt.setEditable(true);

    horaCombo.setEnabled(true);
    minCombo.setEnabled(true);

    saveTtoBtn.setEnabled(true);
    editarBtn.setEnabled(false);

    //toggle al entrar
    habilitarDosisLenta(insulinaCheck.isSelected());
}




    
    public void bloquearCampos() {
        nombreTxt.setEnabled(false);
        rutTxt.setEnabled(false);
        
        dietaTxt.setEnabled(true);
        medsTxt.setEnabled(true);
        sosCheck.setEnabled(true);
        insulinaCheck.setEnabled(true);
        dosisTxt.setEnabled(true);
        freqTxt.setEnabled(true);
       
    }

    public JComboBox<String> getHoraCombo() {
        return horaCombo;
    }

    public JComboBox<String> getMinCombo() {
        return minCombo;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rutTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dietaTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        medsTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        freqTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dosisTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        volverBtn = new javax.swing.JButton();
        sosCheck = new javax.swing.JCheckBox();
        saveTtoBtn = new javax.swing.JButton();
        horaCombo = new javax.swing.JComboBox<>();
        minCombo = new javax.swing.JComboBox<>();
        insulinaCheck = new javax.swing.JCheckBox();
        editarBtn = new javax.swing.JButton();

        jLabel1.setText("Tratamiento del paciente");

        jLabel2.setText("Nombre:");

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Rut:");

        rutTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Datos del paciente:");

        jLabel5.setText("Dieta recomendada:");

        dietaTxt.setColumns(5);
        dietaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietaTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Medicamentos orales:");

        medsTxt.setColumns(5);
        medsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medsTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Datos del tratamiento:");

        jLabel8.setText("Insulina SOS");

        jLabel9.setText("Insulina lenta diaria:");

        freqTxt.setColumns(5);
        freqTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freqTxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Dosis insulina lenta: ");

        dosisTxt.setColumns(5);
        dosisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosisTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("Frecuencia controles (hrs):");

        jLabel12.setText("Primer control:");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        sosCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosCheckActionPerformed(evt);
            }
        });

        saveTtoBtn.setText("Guardar");
        saveTtoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTtoBtnActionPerformed(evt);
            }
        });

        horaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        insulinaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insulinaCheckActionPerformed(evt);
            }
        });

        editarBtn.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(volverBtn)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarBtn)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(28, 28, 28)
                                        .addComponent(rutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(28, 28, 28)
                                        .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(saveTtoBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addComponent(medsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(dietaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(dosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(horaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(minCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(freqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insulinaCheck)
                                    .addComponent(sosCheck))
                                .addGap(54, 54, 54)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(volverBtn)
                    .addComponent(editarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dietaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(medsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(sosCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insulinaCheck)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(freqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(horaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveTtoBtn)
                        .addGap(28, 28, 28))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dietaTxt, dosisTxt, freqTxt, jLabel1, jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, medsTxt, nombreTxt, rutTxt, volverBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void rutTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutTxtActionPerformed

    private void dietaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dietaTxtActionPerformed

    private void medsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medsTxtActionPerformed

    private void freqTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freqTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freqTxtActionPerformed

    private void dosisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosisTxtActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverBtnActionPerformed

    private void sosCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sosCheckActionPerformed

    private void saveTtoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTtoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveTtoBtnActionPerformed

    private void insulinaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insulinaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insulinaCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dietaTxt;
    private javax.swing.JTextField dosisTxt;
    private javax.swing.JButton editarBtn;
    private javax.swing.JTextField freqTxt;
    private javax.swing.JComboBox<String> horaCombo;
    private javax.swing.JCheckBox insulinaCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField medsTxt;
    private javax.swing.JComboBox<String> minCombo;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField rutTxt;
    private javax.swing.JButton saveTtoBtn;
    private javax.swing.JCheckBox sosCheck;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
