/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Diavuru
 */
public class PanelMenuCuidador extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuCuidador
     */
    public PanelMenuCuidador() {
        initComponents();
    }

    public JButton getEditPctBtn() {
        return EditPctBtn;
    }

    public JButton getAddPctBtn() {
        return addPctBtn;
    }

    public JButton getListarPctBtn() {
        return listarPctBtn;
    }

    public JTable getPctTabla() {
        return pctTabla;
    }

    public JButton getLogoutBtn() {
        return logoutBtn;
    }
    
    public JButton getRegistrarGlicemiaBtn() {
        return registrarGlicemiaBtn;
    }

    public JButton getVerTratamientoBtn() {
        return verTratamientoBtn;
    }

    
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(
                this,               // Componente padre (la propia ventana)
                mensaje,            // Texto del error
                "Error",            // Título de la ventana de diálogo
                JOptionPane.ERROR_MESSAGE  // Icono de error
        );
    }
    
    public void mostrarInfo(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditPctBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pctTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addPctBtn = new javax.swing.JButton();
        listarPctBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        registrarGlicemiaBtn = new javax.swing.JButton();
        verTratamientoBtn = new javax.swing.JButton();

        EditPctBtn.setText("Editar Paciente");

        pctTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(pctTabla);

        jLabel1.setText("Menu cuidador");

        addPctBtn.setText("Agregar Paciente");
        addPctBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPctBtnActionPerformed(evt);
            }
        });

        listarPctBtn.setText("Listar Paciente");

        logoutBtn.setText("Cerrar Sesión");

        registrarGlicemiaBtn.setText("Glicemias");

        verTratamientoBtn.setText("Ver Tratamiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(addPctBtn)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listarPctBtn)
                                .addGap(18, 18, 18)
                                .addComponent(EditPctBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(logoutBtn)))))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(registrarGlicemiaBtn)
                .addGap(45, 45, 45)
                .addComponent(verTratamientoBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(logoutBtn))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarGlicemiaBtn)
                    .addComponent(verTratamientoBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPctBtn)
                    .addComponent(listarPctBtn)
                    .addComponent(EditPctBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPctBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPctBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPctBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditPctBtn;
    private javax.swing.JButton addPctBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarPctBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable pctTabla;
    private javax.swing.JButton registrarGlicemiaBtn;
    private javax.swing.JButton verTratamientoBtn;
    // End of variables declaration//GEN-END:variables
}
