package vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

import java.awt.Color;
import java.awt.Component;
import java.awt.BorderLayout;

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import modelo.Paciente;



public class PanelMenuCuidador extends javax.swing.JPanel {

    private javax.swing.JPanel panelAlertas;

    
        public PanelMenuCuidador() {
    initComponents();

    // ===== CONTENEDOR DE ALERTAS (SIN TOCAR GROUPLAYOUT) =====
    panelAlertas = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelAlertas.add(alertasScroll, java.awt.BorderLayout.CENTER);

    // ⚠️ NO SE OCULTA EL SCROLL, SOLO SE DESHABILITA
    activoCheck.setEnabled(false);

    alertasScroll.setEnabled(false);
    alertasTabla.setEnabled(false);

    // ===== MODELO FIJO PARA ALERTAS =====
    alertasTabla.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Fecha", "Hora", "Tipo"}
    ));
}



public void habilitarPanelPaciente(boolean habilitado) {

    activoCheck.setEnabled(habilitado);

    alertasScroll.setEnabled(habilitado);
    alertasTabla.setEnabled(habilitado);

    if (!habilitado) {
        DefaultTableModel modelo =
            (DefaultTableModel) alertasTabla.getModel();
        modelo.setRowCount(0); // limpia alertas
    }
}

    public void limpiarAlertas() {
    DefaultTableModel modelo =
        (DefaultTableModel) alertasTabla.getModel();
    modelo.setRowCount(0);
}

    
public void aplicarRenderPacientes(java.util.List<Paciente> pacientes) {
    pctTabla.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            Paciente p = pacientes.get(row);

            if (!p.isActivo()) {
                c.setForeground(Color.GRAY); 
            } else {
                c.setForeground(isSelected ? table.getSelectionForeground() : Color.BLACK);
            }

            return c;
        }
    });
}

    
    
    
   
    public JCheckBox getActivoCheck() {
        return activoCheck;
    }

    public JTable getAlertasTabla() {
        return alertasTabla;
    }

    public JScrollPane getAlertasScroll() {
        return alertasScroll;
    }

    public JTable getPctTabla() {
        return pctTabla;
    }

    public JTextField getBuscarRutTxt() {
        return buscarRutTxt;
    }
    
    public javax.swing.JPanel getPanelAlertas() {
        return panelAlertas;
    }


    public JButton getAddPctBtn() {
        return addPctBtn;
    }

    public JButton getEditPctBtn() {
        return EditPctBtn;
    }

    public JButton getListarPctBtn() {
        return listarPctBtn;
    }

    public JButton getRegistrarGlicemiaBtn() {
        return registrarGlicemiaBtn;
    }

    public JButton getVerTratamientoBtn() {
        return verTratamientoBtn;
    }

    public JButton getLogoutBtn() {
        return logoutBtn;
    }
    
    
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(
                this,               // Componente padre (la propia ventana)
                mensaje,            // Texto del error
                "Error",            // Título de la ventana de diálogo
                JOptionPane.ERROR_MESSAGE  // Icono de error
        );
    }
    
    public void mostrarInfo(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditPctBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pctTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addPctBtn = new javax.swing.JButton();
        listarPctBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        registrarGlicemiaBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        verTratamientoBtn = new javax.swing.JButton();
        buscarRutTxt = new javax.swing.JTextField();
        alertasScroll = new javax.swing.JScrollPane();
        alertasTabla = new javax.swing.JTable();
        activoCheck = new javax.swing.JCheckBox();

        EditPctBtn.setText("Editar Paciente");

        pctTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(pctTabla);

        jLabel1.setText("Menu cuidador");

        addPctBtn.setText("Agregar Paciente");
        addPctBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPctBtnActionPerformed(evt);
            }
        });

        listarPctBtn.setText("Listar Paciente");

        logoutBtn.setText("Cerrar Sesión");

        registrarGlicemiaBtn.setText("Glicemias");

        jLabel2.setText("Buscar RUT:");

        verTratamientoBtn.setText("Ver Tratamiento");

        buscarRutTxt.setColumns(12);
        buscarRutTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRutTxtActionPerformed(evt);
            }
        });

        alertasTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        alertasScroll.setViewportView(alertasTabla);

        activoCheck.setText("Activar / Desactivar paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addPctBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel1)))
                                .addGap(18, 18, 18)
                                .addComponent(listarPctBtn)
                                .addGap(18, 18, 18)
                                .addComponent(EditPctBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logoutBtn)
                                    .addComponent(alertasScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(buscarRutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activoCheck)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(registrarGlicemiaBtn)
                        .addGap(54, 54, 54)
                        .addComponent(verTratamientoBtn)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarRutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarGlicemiaBtn)
                    .addComponent(verTratamientoBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPctBtn)
                    .addComponent(listarPctBtn)
                    .addComponent(EditPctBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(activoCheck)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(alertasScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn)
                        .addGap(33, 33, 33))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPctBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPctBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPctBtnActionPerformed

    private void buscarRutTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRutTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarRutTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditPctBtn;
    private javax.swing.JCheckBox activoCheck;
    private javax.swing.JButton addPctBtn;
    private javax.swing.JScrollPane alertasScroll;
    private javax.swing.JTable alertasTabla;
    private javax.swing.JTextField buscarRutTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarPctBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable pctTabla;
    private javax.swing.JButton registrarGlicemiaBtn;
    private javax.swing.JButton verTratamientoBtn;
    // End of variables declaration//GEN-END:variables
}
